#This docker compose file is used to work locally with the project

version: '3.8'
services:
  db:
    image: mysql
    container_name: backoffice_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - web

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: backoffice_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - web

  # Symfony apache project container
  www:
    build: docker/php
    container_name: backoffice_front
    ports:
      - '8741:80'
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - web

networks:
  web:

volumes:
  db-data:
